### ISSUE TITLE
[Suggestion] Quality and LoD settings

### ISSUE THREAD

**Issue by AlienXtream** [Talon396/EnhancedWeather#50] opened 2024-04-02 01:18 UTC
more settings to fine tune the rendering of the clouds for performance, including resolution, visual density, a "fast mode" that only renders a single planar cloud layer (like fast clouds), and possibly some form of LoD.

**Comment by TalonFloof** [comment] 2024-04-13 13:39
Duplicate of #48

**Closed as not planned by TalonFloof** 2024-04-13 13:39 UTC
